org.knime.knime_image_processing: # {group_id}.{name} from the knime.yml 
  src: /Users/quynhanhnguyen/Desktop/knime-image-processing/knime_img_proc/ # Path to folder containing the extension files
  conda_env_path: /opt/anaconda3/envs/knime_image_processing_env # Path to the Python environment to use
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform